name: todoapp
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.2.0+3.2

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  collection: ^1.15.0
  connectivity: ^3.0.4
  flutter_easyloading: ^3.0.0
  flutter_icons: ^1.1.0
  flutter_image_compress: ^1.0.0
  flutter_k_chart: ^0.2.0
  flutter_local_notifications: ^6.0.0
  flutter_sound: ^8.1.4
  flutter_staggered_animations: ^1.0.0
  google_sign_in: ^5.0.3
  googleapis: ^3.0.0
  hive: ^2.0.0
  hive_flutter: ^1.0.0
  image_picker: ^0.7.5+3
  just_audio: ^0.7.5
  path_provider: ^2.0.1
  permission_handler: ^8.0.1
  provider: ^5.0.0
  shimmer: ^2.0.0
  splashscreen: ^1.3.5
  undo: ^1.3.1
  url_launcher: ^6.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.0.4
  flutter_launcher_icons: ^0.9.0
  hive_generator: ^1.0.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/todoapplogo.png"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/lang/en.json
    - assets/lang/fa.json
    - assets/images/todoapplogo.png
    - assets/images/notask.png
    - assets/images/plant.png
    - assets/images/deepwork.png
    - assets/images/family.png
    - assets/images/paradise.png
    - assets/images/pioritize.png
    - assets/images/SplashScreenBlack.gif
    - assets/images/SplashScreenWhite.gif
    - assets/images/coffee.png
    - assets/images/dogecoin.png
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    #   - family: BalsamiqSans
    #     fonts:
    #       - asset: assets/fonts/BalsamiqSans-Regular.ttf
    #       - asset: assets/fonts/BalsamiqSans-Bold.ttf
    #       - asset: assets/fonts/BalsamiqSans-BoldItalic.ttf
    #       - asset: assets/fonts/BalsamiqSans-Italic.ttf
    - family: Dubai
      fonts:
        - asset: assets/fonts/Dubai-Regular.otf
        - asset: assets/fonts/Dubai-Bold.otf
        - asset: assets/fonts/Dubai-Light.otf
        - asset: assets/fonts/Dubai-Medium.otf
          style: italic
    - family: Ubuntu Condensed
      fonts:
        - asset: assets/fonts/UbuntuCondensed-Regular.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
